// Automatically generated from README.md
const APIS_DATA = [
  {
    "name": "IPstack",
    "category": "Other",
    "description": "Locate and Identify Website Visitors by IP Address",
    "url": "https://ipstack.com/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers",
    "auth": "[<img src=\"https://run.pstmn.io/button.svg\" alt=\"Run In Postman\" style=\"width: 128px; height: 32px;\">](https://god.gw.postman.com/run-collection/10131015-55145132-244c-448c-8e6f-878[...]",
    "https": "",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Marketstack",
    "category": "Other",
    "description": "Free, easy-to-use REST API interface delivering worldwide stock market data in JSON format",
    "url": "https://marketstack.com/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers",
    "auth": "[<img src=\"https://run.pstmn.io/button.svg\" alt=\"Run In Postman\" style=\"width: 128px; height: 32px;\">](https://god.gw.postman.com/run-collection/10131015-9cbac391-3611-4f50-9bfd-d24[...]",
    "https": "",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Weatherstack",
    "category": "Other",
    "description": "Retrieve instant, accurate weather information for any location in the world in lightweight JSON format",
    "url": "https://weatherstack.com/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers",
    "auth": "[<img src=\"https://run.pstmn.io/button.svg\" alt=\"Run In Postman\" style=\"width: 128px; height: 32px;\">](https://god.gw.postman.com/run-collection/10131015-276c4312-f682-425d-b6b1-0f8[...]",
    "https": "",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Numverify",
    "category": "Other",
    "description": "Global Phone Number Validation & Lookup JSON API",
    "url": "https://numverify.com/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers ",
    "auth": "[<img src=\"https://run.pstmn.io/button.svg\" alt=\"Run In Postman\" style=\"width: 128px; height: 32px;\">](https://god.gw.postman.com/run-collection/10131015-0760d25e-b802-412e-b0e4-26e[...]",
    "https": "",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Fixer",
    "category": "Other",
    "description": "Fixer is a simple and lightweight API for current and historical foreign exchange (forex) rates.",
    "url": "https://fixer.io/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers",
    "auth": "[<img src=\"https://run.pstmn.io/button.svg\" alt=\"Run In Postman\" style=\"width: 128px; height: 32px;\">](https://god.gw.postman.com/run-collection/10131015-0d9c66b3-5f1a-42ed-a5ca-379[...]",
    "https": "",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Aviationstack",
    "category": "Other",
    "description": "Free, real-time flight status and global Aviation data API",
    "url": "https://aviationstack.com/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers",
    "auth": "[<img src=\"https://run.pstmn.io/button.svg\" alt=\"Run In Postman\" style=\"width: 128px; height: 32px;\">](https://god.gw.postman.com/run-collection/10131015-72ee0d35-018e-4370-a2b6-a66[...]",
    "https": "",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Zenserp",
    "category": "Other",
    "description": "Fast, Accurate Google Search Data Built for Developers",
    "url": "https://zenserp.com/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers",
    "auth": "[<img src=\"https://run.pstmn.io/button.svg\" alt=\"Run In Postman\" style=\"width: 128px; height: 32px;\">](https://god.gw.postman.com/run-collection/10131015-a3d63243-081e-4961-a2f0-39c[...]",
    "https": "",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Screenshotlayer",
    "category": "Other",
    "description": "Capture highly customizable screenshots of any website",
    "url": "https://screenshotlayer.com/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers",
    "auth": "[Documentation](https://docs.apilayer.com/screenshotlayer/docs/api-documentation?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers)",
    "https": "",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Exchangerate Host",
    "category": "Other",
    "description": "Real-time current and historical foreign exchange and crypto rates",
    "url": "https://exchangerate.host/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers",
    "auth": "[Documentation](https://docs.apilayer.com/Exchangerate/docs/api-documentation?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers)",
    "https": "",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Mailboxlayer",
    "category": "Other",
    "description": "Email Validation & Verification JSON API for Developers",
    "url": "https://mailboxlayer.com/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers",
    "auth": "[Documentation](https://docs.apilayer.com/mailboxlayer/docs/api-documentation?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers)",
    "https": "",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "AdoptAPet",
    "category": "Animals",
    "description": "Resource to help get pets adopted",
    "url": "https://www.adoptapet.com/public/apis/pet_list.html",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Axolotl",
    "category": "Animals",
    "description": "Collection of axolotl pictures and facts",
    "url": "https://theaxolotlapi.netlify.app/",
    "auth": "No",
    "https": "Yes",
    "cors": "No",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Cat Facts",
    "category": "Animals",
    "description": "Daily cat facts",
    "url": "https://alexwohlbruck.github.io/cat-facts/",
    "auth": "No",
    "https": "Yes",
    "cors": "No",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Cat Facts",
    "category": "Animals",
    "description": "Random cat facts",
    "url": "https://catfact.ninja/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Cataas",
    "category": "Animals",
    "description": "Cat as a service (cats pictures and gifs)",
    "url": "https://cataas.com/",
    "auth": "No",
    "https": "Yes",
    "cors": "No",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Cats",
    "category": "Animals",
    "description": "Pictures of cats from Tumblr",
    "url": "https://docs.thecatapi.com/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "No",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Dog Facts",
    "category": "Animals",
    "description": "Random dog facts",
    "url": "https://dukengn.github.io/Dog-facts-API/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Dog Facts",
    "category": "Animals",
    "description": "Random facts of Dogs",
    "url": "https://kinduff.github.io/dog-api/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Dogs",
    "category": "Animals",
    "description": "Based on the Stanford Dogs Dataset",
    "url": "https://dog.ceo/dog-api/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "eBird",
    "category": "Animals",
    "description": "Retrieve recent or notable birding observations within a region",
    "url": "https://documenter.getpostman.com/view/664302/S1ENwy59",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "No",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "FishWatch",
    "category": "Animals",
    "description": "Information and pictures about individual fish species",
    "url": "https://www.fishwatch.gov/developers",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "HTTP Cat",
    "category": "Animals",
    "description": "Cat for every HTTP Status",
    "url": "https://http.cat/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "HTTP Dog",
    "category": "Animals",
    "description": "Dogs for every HTTP response status code",
    "url": "https://http.dog/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "IUCN",
    "category": "Animals",
    "description": "IUCN Red List of Threatened Species",
    "url": "http://apiv3.iucnredlist.org/api/v3/docs",
    "auth": "apiKey",
    "https": "No",
    "cors": "No",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "MeowFacts",
    "category": "Animals",
    "description": "Get random cat facts",
    "url": "https://github.com/wh-iterabb-it/meowfacts",
    "auth": "No",
    "https": "Yes",
    "cors": "No",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Movebank",
    "category": "Animals",
    "description": "Movement and Migration data of animals",
    "url": "https://github.com/movebank/movebank-api-doc",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Petfinder",
    "category": "Animals",
    "description": "Petfinder is dedicated to helping pets find homes, another resource to get pets adopted",
    "url": "https://www.petfinder.com/developers/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "PlaceBear",
    "category": "Animals",
    "description": "Placeholder bear pictures",
    "url": "https://placebear.com/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "PlaceDog",
    "category": "Animals",
    "description": "Placeholder Dog pictures",
    "url": "https://place.dog",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "PlaceKitten",
    "category": "Animals",
    "description": "Placeholder Kitten pictures",
    "url": "https://placekitten.com/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "RandomDog",
    "category": "Animals",
    "description": "Random pictures of dogs",
    "url": "https://random.dog/woof.json",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "RandomDuck",
    "category": "Animals",
    "description": "Random pictures of ducks",
    "url": "https://random-d.uk/api",
    "auth": "No",
    "https": "Yes",
    "cors": "No",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "RandomFox",
    "category": "Animals",
    "description": "Random pictures of foxes",
    "url": "https://randomfox.ca/floof/",
    "auth": "No",
    "https": "Yes",
    "cors": "No",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "RescueGroups",
    "category": "Animals",
    "description": "Adoption",
    "url": "https://userguide.rescuegroups.org/display/APIDG/API+Developers+Guide+Home",
    "auth": "No",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Shibe.Online",
    "category": "Animals",
    "description": "Random pictures of Shiba Inu, cats or birds",
    "url": "http://shibe.online/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "The Dog",
    "category": "Animals",
    "description": "A public service all about Dogs, free to use when making your fancy new App, Website or Service",
    "url": "https://thedogapi.com/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "No",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "xeno-canto",
    "category": "Animals",
    "description": "Bird recordings",
    "url": "https://xeno-canto.org/explore/api",
    "auth": "No",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Zoo Animals",
    "category": "Animals",
    "description": "Facts and pictures of zoo animals",
    "url": "https://zoo-animal-api.herokuapp.com/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "AniAPI",
    "category": "Anime",
    "description": "Anime discovery, streaming & syncing with trackers",
    "url": "https://aniapi.com/docs/",
    "auth": "OAuth",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "AniDB",
    "category": "Anime",
    "description": "Anime Database",
    "url": "https://wiki.anidb.net/HTTP_API_Definition",
    "auth": "apiKey",
    "https": "No",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "AniList",
    "category": "Anime",
    "description": "Anime discovery & tracking",
    "url": "https://github.com/AniList/ApiV2-GraphQL-Docs",
    "auth": "OAuth",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "AnimeChan",
    "category": "Anime",
    "description": "Anime quotes (over 10k+)",
    "url": "https://github.com/RocktimSaikia/anime-chan",
    "auth": "No",
    "https": "Yes",
    "cors": "No",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "AnimeFacts",
    "category": "Anime",
    "description": "Anime Facts (over 100+)",
    "url": "https://chandan-02.github.io/anime-facts-rest-api/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "AnimeNewsNetwork",
    "category": "Anime",
    "description": "Anime industry news",
    "url": "https://www.animenewsnetwork.com/encyclopedia/api.php",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Catboy",
    "category": "Anime",
    "description": "Neko images, funny GIFs & more",
    "url": "https://catboys.com/api",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Danbooru Anime",
    "category": "Anime",
    "description": "Thousands of anime artist database to find good anime art",
    "url": "https://danbooru.donmai.us/wiki_pages/help:api",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Jikan",
    "category": "Anime",
    "description": "Unofficial MyAnimeList API",
    "url": "https://jikan.moe",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Kitsu",
    "category": "Anime",
    "description": "Anime discovery platform",
    "url": "https://kitsu.docs.apiary.io/",
    "auth": "OAuth",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "MangaDex",
    "category": "Anime",
    "description": "Manga Database and Community",
    "url": "https://api.mangadex.org/docs.html",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Mangapi",
    "category": "Anime",
    "description": "Translate manga pages from one language to another",
    "url": "https://rapidapi.com/pierre.carcellermeunier/api/mangapi3/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "MyAnimeList",
    "category": "Anime",
    "description": "Anime and Manga Database and Community",
    "url": "https://myanimelist.net/clubs.php?cid=13727",
    "auth": "OAuth",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "NekosBest",
    "category": "Anime",
    "description": "Neko Images & Anime roleplaying GIFs",
    "url": "https://docs.nekos.best",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Shikimori",
    "category": "Anime",
    "description": "Anime discovery, tracking, forum, rates",
    "url": "https://shikimori.one/api/doc",
    "auth": "OAuth",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Studio Ghibli",
    "category": "Anime",
    "description": "Resources from Studio Ghibli films",
    "url": "https://ghibliapi.herokuapp.com",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Trace Moe",
    "category": "Anime",
    "description": "A useful tool to get the exact scene of an anime from a screenshot",
    "url": "https://soruly.github.io/trace.moe-api/#/",
    "auth": "No",
    "https": "Yes",
    "cors": "No",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Waifu.im",
    "category": "Anime",
    "description": "Get waifu pictures from an archive of over 4000 images and multiple tags",
    "url": "https://waifu.im/docs",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Waifu.pics",
    "category": "Anime",
    "description": "Image sharing platform for anime images",
    "url": "https://waifu.pics/docs",
    "auth": "No",
    "https": "Yes",
    "cors": "No",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "AbuseIPDB",
    "category": "Anti-Malware",
    "description": "IP/domain/URL reputation",
    "url": "https://docs.abuseipdb.com/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "AlienVault Open Threat Exchange (OTX)",
    "category": "Anti-Malware",
    "description": "IP/domain/URL reputation",
    "url": "https://otx.alienvault.com/api",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "CAPEsandbox",
    "category": "Anti-Malware",
    "description": "Malware execution and analysis",
    "url": "https://capev2.readthedocs.io/en/latest/usage/api.html",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Google Safe Browsing",
    "category": "Anti-Malware",
    "description": "Google Link/Domain Flagging",
    "url": "https://developers.google.com/safe-browsing/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "MalDatabase",
    "category": "Anti-Malware",
    "description": "Provide malware datasets and threat intelligence feeds",
    "url": "https://maldatabase.com/api-doc.html",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "MalShare",
    "category": "Anti-Malware",
    "description": "Malware Archive / file sourcing",
    "url": "https://malshare.com/doc.php",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "No",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "MalwareBazaar",
    "category": "Anti-Malware",
    "description": "Collect and share malware samples",
    "url": "https://bazaar.abuse.ch/api/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Metacert",
    "category": "Anti-Malware",
    "description": "Metacert Link Flagging",
    "url": "https://metacert.com/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "NoPhishy",
    "category": "Anti-Malware",
    "description": "Check links to see if they're known phishing attempts",
    "url": "https://rapidapi.com/Amiichu/api/exerra-phishing-check/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Phisherman",
    "category": "Anti-Malware",
    "description": "IP/domain/URL reputation",
    "url": "https://phisherman.gg/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Scanii",
    "category": "Anti-Malware",
    "description": "Simple REST API that can scan submitted documents/files for the presence of threats",
    "url": "https://docs.scanii.com/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "URLhaus",
    "category": "Anti-Malware",
    "description": "Bulk queries and Download Malware Samples",
    "url": "https://urlhaus-api.abuse.ch/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "URLScan.io",
    "category": "Anti-Malware",
    "description": "Scan and Analyse URLs",
    "url": "https://urlscan.io/about-api/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "VirusTotal",
    "category": "Anti-Malware",
    "description": "VirusTotal File/URL Analysis",
    "url": "https://www.virustotal.com/en/documentation/public-api/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Web of Trust",
    "category": "Anti-Malware",
    "description": "IP/domain/URL reputation",
    "url": "https://support.mywot.com/hc/en-us/sections/360004477734-API-",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Améthyste",
    "category": "Art & Design",
    "description": "Generate images for Discord users",
    "url": "https://api.amethyste.moe/",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Art Institute of Chicago",
    "category": "Art & Design",
    "description": "Art",
    "url": "https://api.artic.edu/docs/",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Colormind",
    "category": "Art & Design",
    "description": "Color scheme generator",
    "url": "http://colormind.io/api-access/",
    "auth": "No",
    "https": "No",
    "cors": "Unknown",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "ColourLovers",
    "category": "Art & Design",
    "description": "Get various patterns, palettes and images",
    "url": "http://www.colourlovers.com/api",
    "auth": "No",
    "https": "No",
    "cors": "Unknown",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Cooper Hewitt",
    "category": "Art & Design",
    "description": "Smithsonian Design Museum",
    "url": "https://collection.cooperhewitt.org/api",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Dribbble",
    "category": "Art & Design",
    "description": "Discover the world's top designers & creatives",
    "url": "https://developer.dribbble.com",
    "auth": "OAuth",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Pro",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "EmojiHub",
    "category": "Art & Design",
    "description": "Get emojis by categories and groups",
    "url": "https://github.com/cheatsnake/emojihub",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Europeana",
    "category": "Art & Design",
    "description": "European Museum and Galleries content",
    "url": "https://pro.europeana.eu/resources/apis/search",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Harvard Art Museums",
    "category": "Art & Design",
    "description": "Art",
    "url": "https://github.com/harvardartmuseums/api-docs",
    "auth": "apiKey",
    "https": "No",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Icon Horse",
    "category": "Art & Design",
    "description": "Favicons for any website, with fallbacks",
    "url": "https://icon.horse",
    "auth": "No",
    "https": "Yes",
    "cors": "Yes",
    "tier": "Free",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Iconfinder",
    "category": "Art & Design",
    "description": "Icons",
    "url": "https://developer.iconfinder.com",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  },
  {
    "name": "Icons8",
    "category": "Art & Design",
    "description": "Icons",
    "url": "https://icons8.com/api",
    "auth": "apiKey",
    "https": "Yes",
    "cors": "Unknown",
    "tier": "Standard",
    "price_per_call": 10,
    "is_active": true
  }
];
